### PR TITLE
New checkout

### PR DESCRIPTION
**Pull request by anthonykawa**
This change is [Reviewable](http://localhost:8080/reviews/kawatestorg/testing/14)

### CODE REVIEW

**Review by anthonykawa — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](http://localhost:8080/reviews/kawatestorg/testing/14)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @anthonyk2020)

**Review by anthonykawa — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](http://localhost:8080/reviews/kawatestorg/testing/14)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @anthonyk2020)

**Review by anthonykawa — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](http://localhost:8080/reviews/kawatestorg/testing/14)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @anthonyk2020)

**Review by anthonykawa — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/kawatestorg/testing/14)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @anthonyk2020)

___
*[.github/workflows/enterprise.yaml, line 105 at r1](http://localhost:8080/reviews/kawatestorg/testing/14#-MYgasRm60EIaAldPuUh:-MYgasRm60EIaAldPuUi:b-aif6lw) ([raw file](https://github.com/kawatestorg/testing/blob/679b632b91b167843c8b65b7387b9d4a6c16a017/.github/workflows/enterprise.yaml#L105)):*
> ```YAML
>         with:
>           repository: 'TEAMBLAWA/testing'
>           path: 'reviewable-client'
> ```

this is a blocking comment

**Review by anthonyk2020 — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](http://localhost:8080/reviews/kawatestorg/testing/14)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @anthonykawa)

**Review by anthonykawa — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](http://localhost:8080/reviews/kawatestorg/testing/14)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @anthonyk2020)

**Review by anthonykawa — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](http://localhost:8080/reviews/kawatestorg/testing/14)* status: all files reviewed, 1 unresolved discussion (waiting on @anthonykawa)

**Review by anthonykawa — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](http://localhost:8080/reviews/kawatestorg/testing/14)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @anthonykawa)

___
*[Dockerfile, line 2 at r1](http://localhost:8080/reviews/kawatestorg/testing/14#-MYgcscDAdc035KadjhS:-MYgcscEBEGhdQOvb0yR:bb710yj) ([raw file](https://github.com/kawatestorg/testing/blob/d1c1dbf5d719a7faeec17846d331761444c88168/Dockerfile#L2)):*
> ```Dockerfile
> FROM nginx
> WORKDIR /usr/share/nginx/html
> ```

Nope

**Review by anthonykawa — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](http://localhost:8080/reviews/kawatestorg/testing/14)* status: all files reviewed, 2 unresolved discussions (waiting on @anthonykawa)

**Review by anthonykawa — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](http://localhost:8080/reviews/kawatestorg/testing/14)* status: all files reviewed, 1 unresolved discussion (waiting on @anthonykawa)

**Review by anthonykawa — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](http://localhost:8080/reviews/kawatestorg/testing/14)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @anthonykawa)

**Review by anthonyk2020 — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](http://localhost:8080/reviews/kawatestorg/testing/14)* status: all files reviewed, 1 unresolved discussion (waiting on @anthonykawa)

**Review by anthonyk2020 — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](http://localhost:8080/reviews/kawatestorg/testing/14)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @anthonykawa)

**Review by anthonykawa — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/kawatestorg/testing/14)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @anthonykawa)

___
*[Dockerfile, line 1 at r1](http://localhost:8080/reviews/kawatestorg/testing/14#-MYgeDN4AHGqjjPXNJbI:-MYgeDN4AHGqjjPXNJbJ:beo96m2) ([raw file](https://github.com/kawatestorg/testing/blob/d1c1dbf5d719a7faeec17846d331761444c88168/Dockerfile#L1)):*
> ```Dockerfile
> FROM nginx
> ```

new comment

**Review by anthonykawa — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](http://localhost:8080/reviews/kawatestorg/testing/14)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @anthonykawa)

**Review by anthonykawa — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](http://localhost:8080/reviews/kawatestorg/testing/14)* status: all files reviewed, 2 unresolved discussions (waiting on @anthonykawa)

**Review by anthonykawa — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](http://localhost:8080/reviews/kawatestorg/testing/14)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @anthonykawa)

**Review by anthonykawa — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](http://localhost:8080/reviews/kawatestorg/testing/14)* status: all files reviewed, 2 unresolved discussions (waiting on @anthonykawa)

**Review by anthonykawa — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](http://localhost:8080/reviews/kawatestorg/testing/14)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @anthonykawa)

**Review by anthonykawa — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](http://localhost:8080/reviews/kawatestorg/testing/14)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @anthonykawa)

**Review by anthonykawa — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](http://localhost:8080/reviews/kawatestorg/testing/14)* status: all files reviewed, 2 unresolved discussions (waiting on @anthonykawa)

**Review by anthonyk2020 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](http://localhost:8080/reviews/kawatestorg/testing/14)* status: all files reviewed, 2 unresolved discussions (waiting on @anthonykawa)

**Review by anthonykawa — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](http://localhost:8080/reviews/kawatestorg/testing/14)* status: all files reviewed, 2 unresolved discussions (waiting on @anthonykawa)

**Pull request closed without merging**
