### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by anthonykawa**
This change is [Reviewable](https://reviewable.io/reviews/kawatestorg/testing/23)

### CODE REVIEW

**Comment by anthonykawa** [comment]
___
*[app.yaml, line 7 at r1](https://reviewable.io/reviews/kawatestorg/testing/23#-MbdA5aPBuTmy3h-bc4O:-MbdA5aQEZXsD51d7XJu:bizr3b) ([raw file](https://github.com/kawatestorg/testing/blob/054b2c11a36cbebd3ea36c49dfca85cf5db8afec/app.yaml#L7)):*
> ```YAML
> 
> resources:
>   cpu: 0.5
> ```

This is a comment

**Comment by a-unit** [comment]
___
*[app.yaml, line 7 at r1](https://reviewable.io/reviews/kawatestorg/testing/23#-MbdA5aPBuTmy3h-bc4O:-MbdAMIn9Z_ai3MJRB19:b-ui1kul) ([raw file](https://github.com/kawatestorg/testing/blob/054b2c11a36cbebd3ea36c49dfca85cf5db8afec/app.yaml#L7)):*
<details><summary><i>Previously, anthonykawa (Anthony Kawa) wrote…</i></summary><blockquote>

This is a comment
</blockquote></details>

Interesting

**Review by a-unit — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kawatestorg/testing/23)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @anthonyk2020, @anthonykawa, and @frankie95667)

**Review by frankie95667 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kawatestorg/testing/23)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @anthonyk2020, @anthonykawa, and @frankie95667)

**Review by frankie95667 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kawatestorg/testing/23)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @a-unit, @anthonyk2020, and @anthonykawa)

___
*[app.yaml, line 7 at r1](https://reviewable.io/reviews/kawatestorg/testing/23#-MbdA5aPBuTmy3h-bc4O:-MbdAw0G8_mVL3ZyzPMP:b-n8kt5g) ([raw file](https://github.com/kawatestorg/testing/blob/054b2c11a36cbebd3ea36c49dfca85cf5db8afec/app.yaml#L7)):*
<details><summary><i>Previously, a-unit wrote…</i></summary><blockquote>

Interesting
</blockquote></details>

Involved

**Review by anthonyk2020 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kawatestorg/testing/23)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @anthonyk2020)

**Review by anthonyk2020 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kawatestorg/testing/23)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @anthonyk2020)

___
*[app.yaml, line 7 at r1](https://reviewable.io/reviews/kawatestorg/testing/23#-MbdA5aPBuTmy3h-bc4O:-MbdBDd062hNuCTu-1N1:b-roxbvp) ([raw file](https://github.com/kawatestorg/testing/blob/054b2c11a36cbebd3ea36c49dfca85cf5db8afec/app.yaml#L7)):*
<details><summary><i>Previously, frankie95667 wrote…</i></summary><blockquote>

Involved
</blockquote></details>

A new comment

**Review by frankie95667 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kawatestorg/testing/23)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @a-unit and @frankie95667)

**Review by anthonykawa — COMMENTED** [review]
> Dismissed @a-unit from a discussion.
> *[Reviewable](https://reviewable.io/reviews/kawatestorg/testing/23)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @frankie95667)

**Review by anthonykawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kawatestorg/testing/23)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @frankie95667)

___
*[app.yaml, line 25 at r1](https://reviewable.io/reviews/kawatestorg/testing/23#-MbdENmT-R7p4f9npe76:-MbdENmT-R7p4f9npe77:b-psotti) ([raw file](https://github.com/kawatestorg/testing/blob/054b2c11a36cbebd3ea36c49dfca85cf5db8afec/app.yaml#L25)):*
> ```YAML
> env_variables:
>   REVIEWABLE_HOST_URL: https://reviewable-enterprise-test.appspot-preview.com
>   REVIEWABLE_GITHUB_URL: https://github.com
> ```

hmmmmm

**Review by frankie95667 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kawatestorg/testing/23)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @frankie95667)

**Pull request closed without merging**
